### ISSUE TITLE
API keys are public

### ISSUE THREAD

**Issue by epsxy** [bryn-newell/food-truck-bot#7]
In `./config.js` I have notice some tokens and API keys. I was wondering if there are fake data or real keys. I think this may allow other people to impersonate your accounts if they use these keys and thus you may want to delete them from GitHub and generate new ones.

**Comment by bryn-newell** [comment]
This was mostly a fun project during my coding training and has long since been turned off and all but abandoned and disconnected, so not concerned about real data anymore. But you're right it should be in the git ignore, thank you.
